# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses: [192.168.165.30/24]
      routes:
          - to: default
            via: 192.168.165.1
      nameservers:
        addresses: [192.168.165.20, 192.168.165.10]
  version: 2
